In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# Library

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import plotly.express as px
import numpy as np

pd.set_option('display.max_columns', 24)

# Dataset

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/kulyeah/visualisasi data smt 2/spotify-2023.csv', encoding='latin-1')
df.head()

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,in_apple_charts,in_deezer_playlists,in_deezer_charts,in_shazam_charts,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2,2023,7,14,553,147,141381703,43,263,45,10,826,125,B,Major,80,89,83,31,0,8,4
1,LALA,Myke Towers,1,2023,3,23,1474,48,133716286,48,126,58,14,382,92,C#,Major,71,61,74,7,0,10,4
2,vampire,Olivia Rodrigo,1,2023,6,30,1397,113,140003974,94,207,91,14,949,138,F,Major,51,32,53,17,0,31,6
3,Cruel Summer,Taylor Swift,1,2019,8,23,7858,100,800840817,116,207,125,12,548,170,A,Major,55,58,72,11,0,11,15
4,WHERE SHE GOES,Bad Bunny,1,2023,5,18,3133,50,303236322,84,133,87,15,425,144,A,Minor,65,23,80,14,63,11,6

In [ ]:
df.to_excel('spotify-2023.xlsx', index = False )

In [ ]:
df.head(11)

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,in_apple_charts,in_deezer_playlists,in_deezer_charts,in_shazam_charts,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2,2023,7,14,553,147,141381703,43,263,45,10,826,125,B,Major,80,89,83,31,0,8,4
1,LALA,Myke Towers,1,2023,3,23,1474,48,133716286,48,126,58,14,382,92,C#,Major,71,61,74,7,0,10,4
2,vampire,Olivia Rodrigo,1,2023,6,30,1397,113,140003974,94,207,91,14,949,138,F,Major,51,32,53,17,0,31,6
3,Cruel Summer,Taylor Swift,1,2019,8,23,7858,100,800840817,116,207,125,12,548,170,A,Major,55,58,72,11,0,11,15
4,WHERE SHE GOES,Bad Bunny,1,2023,5,18,3133,50,303236322,84,133,87,15,425,144,A,Minor,65,23,80,14,63,11,6
5,Sprinter,"Dave, Central Cee",2,2023,6,1,2186,91,183706234,67,213,88,17,946,141,C#,Major,92,66,58,19,0,8,24
6,Ella Baila Sola,"Eslabon Armado, Peso Pluma",2,2023,3,16,3090,50,725980112,34,222,43,13,418,148,F,Minor,67,83,76,48,0,8,3
7,Columbia,Quevedo,1,2023,7,7,714,43,58149378,25,89,30,13,194,100,F,Major,67,26,71,37,0,11,4
8,fukumean,Gunna,1,2023,5,15,1096,83,95217315,60,210,48,11,953,130,C#,Minor,85,22,62,12,0,28,9
9,La Bebe - Remix,"Peso Pluma, Yng Lvcas",2,2023,3,17,2953,44,553634067,49,110,66,13,339,170,D,Minor,81,56,48,21,0,8,33
10,un x100to,"Bad Bunny, Grupo Frontera",2,2023,4,17,2876,40,505671438,41,205,54,12,251,83,F#,Minor,57,56,72,23,0,27,5

In [ ]:
df.head(26)

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,in_apple_charts,in_deezer_playlists,in_deezer_charts,in_shazam_charts,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2,2023,7,14,553,147,141381703,43,263,45,10,826,125,B,Major,80,89,83,31,0,8,4
1,LALA,Myke Towers,1,2023,3,23,1474,48,133716286,48,126,58,14,382,92,C#,Major,71,61,74,7,0,10,4
2,vampire,Olivia Rodrigo,1,2023,6,30,1397,113,140003974,94,207,91,14,949,138,F,Major,51,32,53,17,0,31,6
3,Cruel Summer,Taylor Swift,1,2019,8,23,7858,100,800840817,116,207,125,12,548,170,A,Major,55,58,72,11,0,11,15
4,WHERE SHE GOES,Bad Bunny,1,2023,5,18,3133,50,303236322,84,133,87,15,425,144,A,Minor,65,23,80,14,63,11,6
5,Sprinter,"Dave, Central Cee",2,2023,6,1,2186,91,183706234,67,213,88,17,946,141,C#,Major,92,66,58,19,0,8,24
6,Ella Baila Sola,"Eslabon Armado, Peso Pluma",2,2023,3,16,3090,50,725980112,34,222,43,13,418,148,F,Minor,67,83,76,48,0,8,3
7,Columbia,Quevedo,1,2023,7,7,714,43,58149378,25,89,30,13,194,100,F,Major,67,26,71,37,0,11,4
8,fukumean,Gunna,1,2023,5,15,1096,83,95217315,60,210,48,11,953,130,C#,Minor,85,22,62,12,0,28,9
9,La Bebe - Remix,"Peso Pluma, Yng Lvcas",2,2023,3,17,2953,44,553634067,49,110,66,13,339,170,D,Minor,81,56,48,21,0,8,33
10,un x100to,"Bad Bunny, Grupo Frontera",2,2023,4,17,2876,40,505671438,41,205,54,12,251,83,F#,Minor,57,56,72,23,0,27,5
11,Super Shy,NewJeans,1,2023,7,7,422,55,58255150,37,202,21,5,168,150,F,Minor,78,52,82,18,0,15,7
12,Flowers,Miley Cyrus,1,2023,1,12,12211,115,1316855716,300,215,745,58,"1,021",118,NaN,Major,71,65,68,6,0,3,7
13,Daylight,David Kushner,1,2023,4,14,3528,98,387570742,80,156,182,24,"1,281",130,D,Minor,51,32,43,83,0,9,3
14,As It Was,Harry Styles,1,2022,3,31,23575,130,2513188493,403,198,863,46,NaN,174,F#,Minor,52,66,73,34,0,31,6
15,Kill Bill,SZA,1,2022,12,8,8109,77,1163093654,183,162,161,12,187,89,G#,Major,64,43,73,5,17,16,4
16,Cupid - Twin Ver.,Fifty Fifty,1,2023,2,24,2942,77,496795686,91,212,78,6,0,120,B,Minor,78,76,59,43,0,34,3
17,What Was I Made For? [From The Motion Picture ...,Billie Eilish,1,2023,7,13,873,104,30546883,80,227,95,24,"1,173",78,NaN,Major,44,14,9,96,0,10,3
18,Classy 101,"Feid, Young Miko",2,2023,3,31,2610,40,335222234,43,100,54,14,187,100,B,Major,86,67,66,14,0,12,16
19,Like Crazy,Jimin,1,2023,3,24,596,68,363369738,8,104,23,2,29,120,G,Major,63,36,73,0,0,36,4
20,LADY GAGA,"Gabito Ballesteros, Junior H, Peso Pluma",3,2023,6,22,332,26,86444842,11,163,10,4,0,140,F,Minor,65,87,74,22,0,42,4
21,I Can See You (Taylorï¿½ï¿½ï¿½s Version) (From...,Taylor Swift,1,2023,7,7,516,38,52135248,73,119,42,1,150,123,F#,Major,69,82,76,6,0,6,3
22,I Wanna Be Yours,Arctic Monkeys,1,2013,1,1,12859,110,1297026226,24,98,582,2,73,135,NaN,Minor,48,44,42,12,2,11,3
23,"Peso Pluma: Bzrp Music Sessions, Vol. 55","Bizarrap, Peso Pluma",2,2023,5,31,1313,40,200647221,17,152,32,11,139,133,F,Minor,85,81,67,26,0,12,5
24,Popular (with Playboi Carti & Madonna) - The I...,"The Weeknd, Madonna, Playboi Carti",3,2023,6,2,1945,87,115364561,74,182,87,14,"1,093",99,C#,Major,85,83,68,7,0,36,20
25,SABOR FRESA,Fuerza Regida,1,2023,6,22,250,26,78300654,16,149,10,5,168,130,G,Minor,79,96,86,9,0,9,9

In [ ]:
df.query('streams == "BPM110KeyAModeMajorDanceability53Valence75Energy69Acousticness7Instrumentalness0Liveness17Speechiness3"')

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,in_apple_charts,in_deezer_playlists,in_deezer_charts,in_shazam_charts,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
574,Love Grows (Where My Rosemary Goes),Edison Lighthouse,1,1970,1,1,2877,0,BPM110KeyAModeMajorDanceability53Valence75Ener...,16,0,54,0,0,110,A,Major,53,75,69,7,0,17,3

In [ ]:
df.drop([574], axis=0, inplace=True)

In [ ]:
df.query('streams == "BPM110KeyAModeMajorDanceability53Valence75Energy69Acousticness7Instrumentalness0Liveness17Speechiness3"')

Empty DataFrame
Columns: [track_name, artist(s)_name, artist_count, released_year, released_month, released_day, in_spotify_playlists, in_spotify_charts, streams, in_apple_playlists, in_apple_charts, in_deezer_playlists, in_deezer_charts, in_shazam_charts, bpm, key, mode, danceability_%, valence_%, energy_%, acousticness_%, instrumentalness_%, liveness_%, speechiness_%]
Index: []

# Info Dataset

In [ ]:
df['streams'] = df['streams'].astype('int')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 952 entries, 0 to 952
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   track_name            952 non-null    object
 1   artist(s)_name        952 non-null    object
 2   artist_count          952 non-null    int64
 3   released_year         952 non-null    int64
 4   released_month        952 non-null    int64
 5   released_day          952 non-null    int64
 6   in_spotify_playlists  952 non-null    int64
 7   in_spotify_charts     952 non-null    int64
 8   streams               952 non-null    int64
 9   in_apple_playlists    952 non-null    int64
 10  in_apple_charts       952 non-null    int64
 11  in_deezer_playlists   952 non-null    object
 12  in_deezer_charts      952 non-null    int64
 13  in_shazam_charts      902 non-null    object
 14  bpm                   952 non-null    int64
 15  key                   857 non-null    object
 16  mode                  952 non-null    object
 17  danceability_%        952 non-null    int64
 18  valence_%             952 non-null    int64
 19  energy_%              952 non-null    int64
 20  acousticness_%        952 non-null    int64
 21  instrumentalness_%    952 non-null    int64
 22  liveness_%            952 non-null    int64
 23  speechiness_%         952 non-null    int64
dtypes: int64(18), object(6)
memory usage: 185.9+ KB

# Pie Chart

In [ ]:
df.groupby(['track_name']).sum()

,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,in_apple_charts,in_deezer_playlists,in_deezer_charts,in_shazam_charts,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
track_name,,,,,,,,,,,,,,,,,,,,,,,
'Till I Collapse,"Eminem, Nate Dogg",2,2002,5,26,22923,0,1695712020,78,46,"2,515",1,0,171,C#,Major,55,10,85,7,0,8,20
(It Goes Like) Nanana - Edit,Peggy Gou,1,2023,6,15,2259,59,57876440,0,0,109,17,0,130,G,Minor,67,96,88,12,19,8,4
10 Things I Hate About You,Leah Kate,1,2022,3,23,1301,0,185550869,23,1,15,0,0,154,G#,Major,54,45,79,1,0,17,5
10:35,"Tiï¿½ï¿½sto, Tate M",2,2022,11,1,4942,26,325592432,190,104,147,18,63,120,G#,Major,70,70,79,7,0,18,10
2 Be Loved (Am I Ready),Lizzo,1,2022,7,14,3682,6,247689123,41,0,158,2,68,156,G,Major,72,92,77,9,0,8,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
you broke me first,Tate McRae,1,2020,4,17,6638,0,1180094974,167,19,318,0,1,124,E,Major,64,8,37,79,0,9,5
ýýý98 Braves,Morgan Wallen,1,2023,3,3,282,0,56533272,6,15,0,0,0,142,D,Major,49,48,67,10,0,26,3
ýýýabcdefu,Gayle,1,2021,8,13,7215,0,1007612429,170,12,575,18,0,122,E,Major,70,42,54,30,0,37,5
ýýýýýýýýýýýý,YOASOBI,1,2023,4,12,356,16,143573775,35,102,8,1,117,166,C#,Major,57,84,94,11,0,37,9
ýýýýýýýýýýýýýýýýýýýýý,Fujii Kaze,1,2020,5,20,685,14,403097450,24,94,9,0,23,158,F#,Minor,60,52,76,17,0,19,5

In [ ]:
df.groupby(['track_name'])['streams'].sum().to_frame().sort_values(['streams'],  ascending = False).head(5)

                                                  streams
track_name
Blinding Lights                                3703895074
Shape of You                                   3562543890
Someone You Loved                              2887241814
Dance Monkey                                   2864791672
Sunflower - Spider-Man: Into the Spider-Verse  2808096550

In [ ]:
top_five_song = df.groupby(['track_name'])['streams'].sum().to_frame().sort_values(['streams'],  ascending = False).head(5)

In [ ]:
top_five_song.index = ['Blinding Lights', 'Shape of You', 'Someone You Loved', 'Dance Monkey', 'Sunflower-Spider-Man']

In [ ]:
top_five_song.index

Index(['Blinding Lights', 'Shape of You', 'Someone You Loved', 'Dance Monkey',
       'Sunflower-Spider-Man'],
      dtype='object')

In [ ]:
top_five_song.values.reshape(5)

array([3703895074, 3562543890, 2887241814, 2864791672, 2808096550])

In [ ]:
labels = top_five_song.index
values = top_five_song.values.reshape(5)

fig = go.Figure(data=[go.Pie(labels=labels, values=values,
                             textinfo='label+percent',
                             insidetextorientation='radial',
                             marker_colors = ['#99B080' ,'#99BC85', '#BFD8AF', '#D4E7C5', '#E1F0DA']
                            )])
fig.update_layout(
    title_text="Top Five Song by Stream Duration")

fig.show()

# Donut Chart

In [ ]:
fig = go.Figure(data=[go.Pie(labels=labels,
                             values=values,
                             textinfo='label+percent',
                             insidetextorientation='radial',
                             marker_colors = ['#6E85B7' ,'#82A0D8', '#B2C8DF', '#C4D7E0', '#DAEAF1'],
                             hole = .6
                            )])
fig.update_layout(
    title_text="Top Five Song by Stream Duration",
    # Add annotations in the center of the donut pies.
    annotations=[dict(text='Top 5 Song', x=0.50, y=0.5, font_size=20, showarrow=False)])

fig.show()

# Tree Map

In [ ]:
top_five_song_id = df.groupby(['track_name'])['streams'].sum().to_frame().sort_values(['streams'],  ascending = False).head(5).index

In [ ]:
df2 = df.set_index('track_name')

In [ ]:
top_five_artist = df2.loc[top_five_song_id, 'artist(s)_name'].values

In [ ]:
df3 = df2.reset_index().set_index('artist(s)_name')

In [ ]:
df4 = df3.loc[top_five_artist]

In [ ]:
df4.reset_index(inplace=True)

In [ ]:
df4

,artist(s)_name,track_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,in_apple_charts,in_deezer_playlists,in_deezer_charts,in_shazam_charts,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
0,The Weeknd,Die For You,1,2016,11,24,2483,59,1647990401,68,21,24,0,259,134,C#,Minor,59,51,52,9,0,15,7
1,The Weeknd,Blinding Lights,1,2019,11,29,43899,69,3703895074,672,199,"3,421",20,NaN,171,C#,Major,50,38,80,0,0,9,7
2,The Weeknd,Save Your Tears,1,2020,3,20,12688,13,1591223784,197,115,112,0,200,118,NaN,Major,68,61,82,2,0,50,3
3,The Weeknd,Reminder,1,2016,11,25,6518,17,684675814,45,85,238,1,47,160,G#,Major,71,40,50,16,0,16,22
4,The Weeknd,Call Out My Name,1,2018,3,29,11087,6,1449799467,151,107,801,1,105,134,C#,Major,45,17,60,21,0,33,4
5,The Weeknd,The Hills,1,2015,5,27,25744,4,1947371785,122,94,"1,992",0,18,136,NaN,Minor,36,12,57,9,0,14,8
6,The Weeknd,After Hours,1,2020,2,19,8084,6,698086140,45,115,218,1,221,109,F,Minor,66,16,57,10,1,12,3
7,The Weeknd,Sacrifice,1,2022,1,7,4440,0,326792833,81,77,133,0,NaN,122,G,Major,70,91,79,3,0,7,10
8,The Weeknd,Is There Someone Else?,1,2022,1,7,2881,6,391251368,13,89,34,0,3,135,A,Minor,70,60,58,4,0,16,3
9,The Weeknd,Out of Time,1,2022,1,7,3711,0,339659802,49,88,62,0,NaN,93,NaN,Minor,65,82,74,27,0,32,5
10,The Weeknd,How Do I Make You Love Me?,1,2022,1,7,1915,0,119238316,7,47,15,0,0,121,G,Minor,80,62,51,2,0,9,8
11,The Weeknd,Gasoline,1,2022,1,7,2297,0,116903579,11,29,14,0,0,123,F#,Minor,74,35,73,0,0,21,5
12,The Weeknd,Less Than Zero,1,2022,1,7,2800,0,200660871,18,77,61,0,1,143,NaN,Major,53,50,79,0,0,8,3
13,The Weeknd,Take My Breath,1,2021,8,6,2597,0,130655803,17,80,38,0,0,121,A#,Minor,70,35,77,1,0,26,4
14,The Weeknd,Best Friends,1,2022,1,7,1292,0,101114984,3,18,14,0,0,87,E,Minor,49,49,59,44,0,35,21
15,The Weeknd,Dawn FM,1,2022,1,7,811,0,53933526,1,8,6,0,0,78,A,Minor,27,10,49,62,0,49,5
16,The Weeknd,Starry Eyes,1,2022,1,7,1014,0,74601456,1,17,11,0,0,86,A,Minor,28,13,41,50,0,19,3
17,The Weeknd,Donï¿½ï¿½ï¿½t Break My,1,2022,1,7,1184,0,63803529,1,5,6,0,0,122,A#,Major,77,25,62,34,0,23,3
18,The Weeknd,A Tale By Quincy,1,2022,1,7,733,0,41924466,0,2,2,0,0,94,F,Minor,46,55,50,71,0,10,11
19,The Weeknd,Every Angel is Terrifying,1,2022,1,7,715,0,37307967,0,1,2,0,0,118,NaN,Major,44,52,94,11,0,4,29
20,The Weeknd,Phantom Regret by Jim,1,2022,1,7,768,0,31959571,1,1,3,0,0,108,A,Minor,46,23,48,75,30,14,4
21,The Weeknd,Take My Breath,1,2021,8,6,6392,0,432702334,174,73,344,0,0,121,G#,Major,75,53,74,2,0,11,5
22,Ed Sheeran,Perfect,1,2017,1,1,16596,13,2559529074,7,0,"2,094",0,0,95,G#,Major,60,17,45,16,0,11,2
23,Ed Sheeran,Shape of You,1,2017,1,6,32181,10,3562543890,33,0,"6,808",7,0,96,C#,Minor,83,93,65,58,0,9,8
24,Ed Sheeran,Eyes Closed,1,2023,3,23,2915,30,195576623,116,69,107,3,675,107,D,Major,78,39,53,30,0,11,6
25,Ed Sheeran,Curtains,1,2023,5,5,715,0,39893489,37,3,27,0,50,176,F#,Minor,50,44,76,10,0,32,5
26,Ed Sheeran,Shivers,1,2021,9,9,10147,30,1302184087,234,71,543,18,NaN,141,D,Major,79,82,86,28,0,4,9
27,Ed Sheeran,Bad Habits,1,2020,9,3,12755,8,1555511105,344,97,945,15,NaN,126,B,Minor,81,59,90,5,0,36,3
28,Ed Sheeran,Thinking Out Loud,1,2014,1,1,33032,0,2280566092,363,129,"3,895",0,28,79,D,Major,78,58,45,47,0,18,3
29,Ed Sheeran,Photograph,1,2014,6,20,18778,3,2236667932,228,105,"2,453",0,84,108,E,Major,61,20,38,61,0,10,5
30,Ed Sheeran,Celestial,1,2022,9,29,1639,0,176474912,86,14,80,0,37,123,D,Major,57,50,85,5,0,16,4
31,Lewis Capaldi,Someone You Loved,1,2018,11,8,17836,53,2887241814,440,125,"1,800",0,NaN,110,C#,Major,50,45,41,75,0,11,3
32,Lewis Capaldi,Before You Go,1,2019,11,1,8327,24,1608045237,205,130,625,0,25,112,D#,Major,45,19,60,63,0,9,6
33,Lewis Capaldi,Forget Me,1,2022,9,9,2520,4,239411309,93,95,84,9,202,102,C#,Minor,67,72,74,30,0,36,4
34,Tones and I,Dance Monkey,1,2019,5,10,24529,0,2864791672,533,167,"3,595",6,NaN,98,F#,Minor,82,54,59,69,0,18,10
35,"Post Malone, Swae Lee",Sunflower - Spider-Man: Into the Spider-Verse,2,2018,10,9,24094,78,2808096550,372,117,843,4,69,90,D,Major,76,91,50,54,0,7,5

In [ ]:
fig = px.treemap(df4, path=[px.Constant("Spotify"), 'artist(s)_name', 'track_name'], values='streams',
                  color='streams',
                  color_continuous_scale='teal',
                  color_continuous_midpoint=np.average(df['streams'], weights=df['streams']))
fig.update_layout(margin = dict(t=50, l=25, r=25, b=25),
                  title_text="Top Five Artist by Song and Stream Duration")
fig.show()

In [ ]:
test

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
11,Afghanistan,Asia,2007,43.828,31889923,974.580338,AFG,4
23,Albania,Europe,2007,76.423,3600523,5937.029526,ALB,8
35,Algeria,Africa,2007,72.301,33333216,6223.367465,DZA,12
47,Angola,Africa,2007,42.731,12420476,4797.231267,AGO,24
59,Argentina,Americas,2007,75.320,40301927,12779.379640,ARG,32
...,...,...,...,...,...,...,...,...
1655,Vietnam,Asia,2007,74.249,85262356,2441.576404,VNM,704
1667,West Bank and Gaza,Asia,2007,73.422,4018332,3025.349798,PSE,275
1679,"Yemen, Rep.",Asia,2007,62.698,22211743,2280.769906,YEM,887
1691,Zambia,Africa,2007,42.384,11746035,1271.211593,ZMB,894
1703,Zimbabwe,Africa,2007,43.487,12311143,469.709298,ZWE,716

In [ ]:
test = px.data.gapminder().query("year == 2007")